import { readFileSync } from 'fs';
import pg from 'pg';
const env = readFileSync('.env.local','utf8');
const url = env.split('\n').find(l=>l.startsWith('DATABASE_URL=')).split('=').slice(1).join('=').trim().replace(/^["']|["']$/g,'');
const c = new pg.Client({ connectionString: url, ssl:{rejectUnauthorized:false} });
await c.connect();
const q = async s => (await c.query(s)).rows;
console.log('Completion-enforce triggers on job_orders:');
console.log(await q(`select tgname, p.proname, t.tgenabled from pg_trigger t join pg_proc p on p.oid=t.tgfoid where t.tgrelid='public.job_orders'::regclass and not t.tgisinternal and p.proname in ('enforce_two_gate_complete','complete_jo_on_charge_confirmed')`));
console.log('charges autocomplete trigger:');
console.log(await q(`select tgname, p.proname from pg_trigger t join pg_proc p on p.oid=t.tgfoid where t.tgrelid='public.charges'::regclass and p.proname='complete_jo_on_charge_confirmed'`));
console.log('search_consignees return columns (source):');
console.log((await q(`select prosrc from pg_proc where proname='search_consignees'`)).map(r=>r.prosrc.slice(0,300)));
console.log('consignees SELECT policy live:');
console.log(await q(`select polname, pg_get_expr(polqual, polrelid) q from pg_policy where polrelid='public.consignees'::regclass and polcmd='r'`));
console.log('jo_ready_to_complete live body excludes confirmed/reversed:');
console.log((await q(`select prosrc from pg_proc where proname='jo_ready_to_complete'`))[0].prosrc.includes("not in ('confirmed','reversed')"));
console.log('confirm_charge_payment gates FINAL erp+bir:');
console.log((await q(`select prosrc from pg_proc where proname='confirm_charge_payment'`))[0].prosrc.includes("FINAL ERP + BIR"));
await c.end();
